# .github/workflows/waka-readme.yml
name: WakaTime Stats Update

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering
  # Optional: Run on push to main/master if you want immediate updates after changing the README
  # push:
  #   branches:
  #     - main # or master, depending on your default branch name

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant permission to write to the repository contents (README.md)
    steps:
      - uses: actions/checkout@v4 # Use a more recent version
      - name: Update WakaTime Stats
        uses: athul/waka-readme@master # Or specify a release version like @v0.2.7 for stability
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # GH_TOKEN is not strictly needed here if using the default GITHUB_TOKEN with correct permissions
          # If you encounter issues, you might need to uncomment GH_TOKEN and create a PAT (see below)
          # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the default token
          # --- Options for athul/waka-readme ---
          # Find more options at https://github.com/athul/waka-readme
          # SHOW_TITLE: "true" # Optional: Display a title for the WakaTime section
          # SHOW_TIME: "true" # Optional: Show total time coded
          # TIME_RANGE: "last_7_days" # Optional: Set the time range (e.g., last_7_days, last_30_days)